#!/bin/sh

#specify your config path in stor1
configs_results_stor1=/stor1/hwang07/tsp/

#use this template folder or copy it to your favored location
template_folder=/stor1/hwang07/insight_files/insight_template

#modify the configs you want to launch on machine in01
for stor1_config in tsp_address_gtoswl1 tsp_address_gtoswl4 tsp_address_gtoswl8 tsp_address_gtoswl16 tsp_address_gtoswl48 tsp_address_lrrswl1 tsp_address_lrrswl4 tsp_address_lrrswl8 tsp_address_lrrswl16 tsp_address_lrrswl48 tsp_address_RR1 tsp_address_RR4 tsp_address_RR8 tsp_address_RR16 tsp_address_RR48 nocache_tsp_address_gtoswl1 nocache_tsp_address_gtoswl4 nocache_tsp_address_gtoswl8 nocache_tsp_address_gtoswl16 nocache_tsp_address_gtoswl48 nocache_tsp_address_lrrswl1 nocache_tsp_address_lrrswl4 nocache_tsp_address_lrrswl8 nocache_tsp_address_lrrswl16 nocache_tsp_address_lrrswl48 nocache_tsp_address_RR1 nocache_tsp_address_RR4 nocache_tsp_address_RR8 nocache_tsp_address_RR16 nocache_tsp_address_RR48
do
cd $configs_results_stor1
cp -r $template_folder $stor1_config
done
