cd /stor1/hwang07/functional_only/GTX480_func_only/CUDA/JPEG/
qsub pbs_JPEG.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/CUDA/BlackScholes/
qsub pbs_BlackScholes.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/CUDA/CONS/
qsub pbs_CONS.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/CUDA/kmeans/
qsub pbs_kmeans.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/CUDA/KMN/
qsub pbs_KMN.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/parboil/lbm/
qsub pbs_lbm.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/rodinia/heartwall/
qsub pbs_heartwall.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/rodinia/pathfinder/
qsub pbs_pathfinder.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/rodinia/lud/
qsub pbs_lud.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/rodinia/srad_v2/
qsub pbs_srad_v2.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/shoc/Reduction/
qsub pbs_Reduction.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/shoc/Scan/
qsub pbs_Scan.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/shoc/Spmv/
qsub pbs_Spmv.pbs
cd /stor1/hwang07/functional_only/GTX480_func_only/shoc/Stencil2D/
qsub pbs_Stencil2D.pbs
