#sh launch_profile_gto.sh
#sh launch_coverage10_noecho_size512_delay_gto.sh
#sh launch_coverage10_noecho_size512_delayonly_gto.sh
#sh launch_profile_onmiss_gto.sh

sh launch_coverage10_noecho_size512_delay_e1_gto.sh
sh launch_coverage10_noecho_size512_delay_e2_gto.sh
sh launch_coverage10_noecho_size512_delay_e3_gto.sh
sh launch_coverage10_noecho_size512_delay_e6_gto.sh