sh recopy_delay_bypass_gto.sh
sh recopy_sizes_delay_gto.sh
sh recopy_sizes_delayonly_gto.sh
sh copy_noecho_delay_bypass_gto.sh
sh copy_noecho_sizes_delay_gto.sh
sh copy_noecho_sizes_delayonly_gto.sh

