#!/bin/sh

sh collect_all_configs_coverage_dynamic1.sh
sh collect_all_configs_coverage_dynamic2.sh
sh collect_all_configs_coverage_dynamic3.sh
sh collect_all_configs_coverage_dynamic4.sh

sh collect_all_configs_coverage_dynamic_nopc1.sh
sh collect_all_configs_coverage_dynamic_nopc2.sh
sh collect_all_configs_coverage_dynamic_nopc3.sh
sh collect_all_configs_coverage_dynamic_nopc4.sh

sh collect_all_configs_coverage_osp_figure15.sh
sh collect_all_configs_coverage_tsp_figure15.sh
sh collect_all_configs_coverage_osp_nopc_figure15.sh
sh collect_all_configs_coverage_tsp_nopc_figure15.sh
sh collect_all_configs_warp_partition_osp_figure15.sh
sh collect_all_configs_warp_partition_tsp_figure15.sh

sh collect_all_configs_warp_partition2_osp_figure15.sh
sh collect_all_configs_warp_partition2_tsp_figure15.sh