#!/bin/sh

sh collect_coverage_coverages_osp_in01.sh
sh collect_coverage_coverages_tsp_in02.sh
sh collect_coverage_rate_osp_in01.sh
sh collect_coverage_rate_tsp_in02.sh
sh collect_coverage_l1mr_osp_in01.sh
sh collect_coverage_l1mr_osp_in02.sh