sh collect_noecho_size128_delay_bypass_gto_all.sh
sh collect_noecho_size128_delay_gto_all.sh
sh collect_noecho_size128_delayonly_gto_all.sh
sh collect_size128_delay_bypass_gto_all.sh
sh collect_size128_delay_gto_all.sh
sh collect_size128_delayonly_gto_all.sh