#!/bin/sh

sh collect_size128_delay_bypass_gto_access_num.sh
sh collect_size128_delay_bypass_gto_act_num.sh
sh collect_size128_delay_bypass_gto_bw.sh
sh collect_size128_delay_bypass_gto_echo.sh
sh collect_size128_delay_bypass_gto_gr_act.sh
sh collect_size128_delay_bypass_gto_gr_num.sh
sh collect_size128_delay_bypass_gto_IPC.sh
sh collect_size128_delay_bypass_gto_l1mr.sh
sh collect_size128_delay_bypass_gto_l2mr.sh
sh collect_size128_delay_bypass_gto_removed.sh
