#rm /sciclone/data10/hwang07/GPU_RESEARCH/amc_collection/coverage10_noecho_delay_sizes512.txt
#rm /sciclone/data10/hwang07/GPU_RESEARCH/amc_collection/coverage10_noecho_delayonly_sizes512.txt
#rm /sciclone/data10/hwang07/GPU_RESEARCH/amc_collection/baseline_size512.txt

#sh collect_coverage10_noecho_size512_delay_gto_all.sh
#sh collect_coverage10_noecho_size512_delayonly_gto_all.sh
#sh collect_profile_all.sh

sh collect_coverage10_noecho_size512_delay_e1_gto_all.sh
sh collect_coverage10_noecho_size512_delay_e2_gto_all.sh
sh collect_coverage10_noecho_size512_delay_e3_gto_all.sh
sh collect_coverage10_noecho_size512_delay_e6_gto_all.sh