#!/bin/sh

sh collect_all_configs_coverage_dynamic1.sh
sh collect_all_configs_coverage_dynamic2.sh
sh collect_all_configs_coverage_dynamic3.sh

sh collect_all_configs_coverage_dynamic_nopc1.sh
sh collect_all_configs_coverage_dynamic_nopc2.sh
sh collect_all_configs_coverage_dynamic_nopc3.sh
